QUESTIONS = [
    {'answer': 'Python is an interpreted, high-level, general-purpose programming '
           'language.',
 'category': 'Basic',
 'code': "print('Hello, Python!')",
 'question': 'What is Python?'},
    {'answer': 'Interpreted, dynamically typed, object-oriented, high-level, '
           'extensive standard library.',
 'category': 'Basic',
 'code': 'x = 5  # Dynamically typed\nprint(type(x))',
 'question': 'What are the key features of Python?'},
    {'answer': 'Lists are mutable, while tuples are immutable.',
 'category': 'Basic',
 'code': 'my_list = [1, 2]\n'
         'my_list[0] = 3  # Works\n'
         '\n'
         'my_tuple = (1, 2)\n'
         '# my_tuple[0] = 3  # TypeError',
 'question': 'What is the difference between a list and a tuple?'},
    {'answer': 'PEP 8 is the style guide for Python code.',
 'category': 'Basic',
 'code': '# Good: x = 1\n# Bad: x=1',
 'question': 'What is PEP 8?'},
    {'answer': 'Python uses a private heap and garbage collection.',
 'category': 'Basic',
 'code': 'import gc\ngc.collect()',
 'question': 'How do you manage memory in Python?'},
    {'answer': 'A namespace is a naming system used to make sure that names are '
           'unique.',
 'category': 'Basic',
 'code': 'def func():\n    local_var = 1\nprint(dir())',
 'question': 'What is a namespace in Python?'},
    {'answer': 'Modules are files containing Python code.',
 'category': 'Basic',
 'code': 'import math\nprint(math.sqrt(16))',
 'question': 'What are Python modules?'},
    {'answer': 'Global variables are outside functions; local variables are '
           'inside.',
 'category': 'Basic',
 'code': "x = 'global'\ndef f():\n    y = 'local'\n    print(y)",
 'question': 'What are local variables and global variables in Python?'},
    {'answer': 'Yes, Python is case sensitive.',
 'category': 'Basic',
 'code': 'Value = 1\n# print(value)  # NameError',
 'question': 'Is Python case sensitive?'},
    {'answer': 'Converting the value of one data type to another.',
 'category': 'Basic',
 'code': "x = int('10')\ny = str(5)",
 'question': 'What is type conversion in Python?'},
    {'answer': 'Download from python.org or use package managers.',
 'category': 'Basic',
 'code': '# On terminal:\n# python --version',
 'question': 'How do you install Python?'},
    {'answer': 'Indentation indicates a block of code.',
 'category': 'Basic',
 'code': "if True:\n    print('Indented block')",
 'question': 'What is indentation in Python?'},
    {'answer': 'Arrays store one data type; lists store any data type.',
 'category': 'Basic',
 'code': "import array\narr = array.array('i', [1, 2])\nlst = [1, 'text']",
 'question': 'What is the difference between Python Arrays and Lists?'},
    {'answer': 'Blocks of code that run when called.',
 'category': 'Basic',
 'code': "def greet(name):\n    return f'Hi {name}'",
 'question': 'What are functions in Python?'},
    {'answer': 'A constructor method called when an object is created.',
 'category': 'Basic',
 'code': 'class MyClass:\n    def __init__(self):\n        self.val = 10',
 'question': 'What is `__init__`?'},
    {'answer': 'A small anonymous function.',
 'category': 'Basic',
 'code': 'square = lambda x: x * x\nprint(square(4))',
 'question': 'What is a lambda function?'},
    {'answer': 'Self represents the instance of the class.',
 'category': 'Basic',
 'code': 'class A:\n    def method(self):\n        print(self)',
 'question': 'Explain self in Python.'},
    {'answer': 'Objects that can be traversed (contain countable values).',
 'category': 'Basic',
 'code': 'it = iter([1, 2])\nprint(next(it))',
 'question': 'What are iterators in Python?'},
    {'answer': 'Using the random module.',
 'category': 'Basic',
 'code': 'import random\nprint(random.randint(1, 10))',
 'question': 'How do you generate random numbers in Python?'},
    {'answer': 'Mechanism to select a range of items from sequences.',
 'category': 'Basic',
 'code': 'lst = [1, 2, 3, 4]\nprint(lst[1:3])',
 'question': 'What is slicing in Python?'},
    {'answer': 'Reserved words for syntax and structure.',
 'category': 'Basic',
 'code': 'import keyword\nprint(keyword.kwlist)',
 'question': 'What are keywords in Python?'},
    {'answer': 'Data given in a variable or constant.',
 'category': 'Basic',
 'code': "s = 'Hello'  # String literal\ni = 10       # Numeric literal",
 'question': 'What are literals in Python?'},
    {'answer': 'Using + operator or extend() method.',
 'category': 'Basic',
 'code': 'a = [1]\nb = [2]\nprint(a + b)',
 'question': 'How can you combine arrays in Python?'},
    {'answer': 'int, float, str, list, tuple, set, dict, bool.',
 'category': 'Basic',
 'code': 'x = [1, 2, 3]  # List',
 'question': 'What are the common built-in data types in Python?'},
    {'answer': 'Using curly braces or dict().',
 'category': 'Basic',
 'code': "d = {'a': 1, 'b': 2}",
 'question': 'How do you create a dictionary?'},
    {'answer': 'A placeholder for future code.',
 'category': 'Basic',
 'code': 'def future_function():\n    pass',
 'question': 'What is the pass statement?'},
    {'answer': '/ is float division; // is floor division.',
 'category': 'Basic',
 'code': 'print(5 / 2)   # 2.5\nprint(5 // 2)  # 2',
 'question': 'What is the difference between / and // operators?'},
    {'answer': 'Using the in keyword.',
 'category': 'Basic',
 'code': "d = {'key': 1}\nprint('key' in d)",
 'question': 'How do you check if a key exists in a dictionary?'},
    {'answer': 'Compares object identity (memory location).',
 'category': 'Basic',
 'code': 'a = [1]\nb = a\nprint(a is b)  # True',
 'question': 'What is the purpose of `is` operator?'},
    {'answer': 'A string literal for documenting code.',
 'category': 'Basic',
 'code': 'def f():\n    """Docstring here."""\n    pass',
 'question': 'What is a docstring?'},
    {'answer': '*args for positional args, **kwargs for keyword args.',
 'category': 'Intermediate',
 'code': 'def f(*args, **kwargs):\n    print(args, kwargs)\nf(1, a=2)',
 'question': 'What is *args and **kwargs?'},
    {'answer': 'Assignment creates a reference to an object.',
 'category': 'Intermediate',
 'code': 'a = [1]\nb = a\nb.append(2)\nprint(a)  # [1, 2]',
 'question': 'Reference vs Assignment?'},
    {'answer': 'Shallow copy: refs remain. Deep copy: everything copied.',
 'category': 'Intermediate',
 'code': 'import copy\na = [[1]]\nb = copy.deepcopy(a)',
 'question': 'Deep copy vs Shallow copy?'},
    {'answer': 'Functions that wrap other functions to modify behavior.',
 'category': 'Intermediate',
 'code': 'def dec(f):\n    return f\n@dec\ndef g(): pass',
 'question': 'What are decorators?'},
    {'answer': 'Functions that yield values one at a time.',
 'category': 'Intermediate',
 'code': 'def gen():\n    yield 1\ng = gen()\nnext(g)',
 'question': 'What is a generator?'},
    {'answer': 'Converting objects to byte stream and back.',
 'category': 'Intermediate',
 'code': 'import pickle\ns = pickle.dumps([1, 2])\nl = pickle.loads(s)',
 'question': 'What is pickling and unpickling?'},
    {'answer': 'Using try, except, else, finally.',
 'category': 'Intermediate',
 'code': "try:\n    x = 1/0\nexcept ZeroDivisionError:\n    print('oops')",
 'question': 'How is Exception Handling done in Python?'},
    {'answer': 'range() in Py3 is an iterator (like Py2 xrange).',
 'category': 'Intermediate',
 'code': 'for i in range(5):\n    print(i)',
 'question': 'What is the difference between range() and xrange()?'},
    {'answer': 'Applies a function to each item in an iterable.',
 'category': 'Intermediate',
 'code': 'm = map(str, [1, 2])\nlist(m)',
 'question': 'What is map function?'},
    {'answer': 'Extracts elements that satisfy a condition.',
 'category': 'Intermediate',
 'code': 'f = filter(lambda x: x > 0, [-1, 1])\nlist(f)',
 'question': 'What is filter function?'},
    {'answer': 'Reduces an iterable to a single value.',
 'category': 'Intermediate',
 'code': 'from functools import reduce\n'
         'r = reduce(lambda x, y: x+y, [1, 2, 3])',
 'question': 'What is reduce function?'},
    {'answer': 'Set has unique elements; dict has key-value pairs.',
 'category': 'Intermediate',
 'code': "s = {1, 2}\nd = {1: 'a'}",
 'question': 'What is the difference between a set and a dictionary?'},
    {'answer': 'A mutex that protects access to Python objects, preventing '
           'multiple threads from running bytecode at once.',
 'category': 'Intermediate',
 'code': '# Impacts CPU-bound threads',
 'question': 'What is the Global Interpreter Lock (GIL)?'},
    {'answer': 'Directories containing modules and __init__.py.',
 'category': 'Intermediate',
 'code': '# my_pkg/\n#   __init__.py\n#   mod.py',
 'question': 'What are Python packages?'},
    {'answer': 'Concise way to create lists.',
 'category': 'Intermediate',
 'code': 'l = [x*x for x in range(3)]',
 'question': 'What is list comprehension?'},
    {'answer': 'Evaluating placeholders in strings (e.g., f-strings).',
 'category': 'Intermediate',
 'code': "x = 5\nprint(f'{x}')",
 'question': 'What is string interpolation?'},
    {'answer': 'Class methods take cls; static methods take nothing.',
 'category': 'Intermediate',
 'code': 'class C:\n'
         '    @classmethod\n'
         '    def cm(cls): pass\n'
         '    @staticmethod\n'
         '    def sm(): pass',
 'question': 'What are class methods and static methods?'},
    {'answer': 'str for users; repr for developers.',
 'category': 'Intermediate',
 'code': 'class C:\n'
         "    def __str__(self): return 'user'\n"
         "    def __repr__(self): return 'dev'",
 'question': 'Difference between `__str__` and `__repr__`?'},
    {'answer': 'One-line conditional.',
 'category': 'Intermediate',
 'code': 'x = 1 if True else 0',
 'question': 'What is the ternary operator in Python?'},
    {'answer': 'Examining objects at runtime.',
 'category': 'Intermediate',
 'code': 'print(dir([]))\nprint(type(5))',
 'question': 'What is introspection or reflection?'},
    {'answer': 'Using multiple except blocks or a tuple.',
 'category': 'Intermediate',
 'code': 'try: pass\nexcept (TypeError, ValueError): pass',
 'question': 'How to handle multiple exceptions?'},
    {'answer': 'Resource management using context managers.',
 'category': 'Intermediate',
 'code': "with open('f.txt', 'w') as f:\n    f.write('hi')",
 'question': 'What is the `with` statement used for?'},
    {'answer': 'Modifying classes/modules at runtime.',
 'category': 'Intermediate',
 'code': 'import math\nmath.sqrt = lambda x: x',
 'question': 'What is monkey patching?'},
    {'answer': 'Yes, a class can inherit from multiple parents.',
 'category': 'Intermediate',
 'code': 'class C(A, B): pass',
 'question': 'Does Python support multiple inheritance?'},
    {'answer': 'Performing same actions in different ways.',
 'category': 'Intermediate',
 'code': 'def func(obj):\n    obj.draw()',
 'question': 'What is polymorphism?'},
    {'answer': 'Wrapping data and methods into a single unit.',
 'category': 'Intermediate',
 'code': 'class C:\n    def __init__(self):\n        self.__private = 1',
 'question': 'What is encapsulation?'},
    {'answer': 'Testing individual units using unittest.',
 'category': 'Intermediate',
 'code': 'import unittest\n'
         'class T(unittest.TestCase):\n'
         '    def test_x(self): self.assertTrue(True)',
 'question': 'What is unit testing in Python?'},
    {'answer': 'Using the super() function.',
 'category': 'Intermediate',
 'code': 'class C(B):\n    def f(self): super().f()',
 'question': 'How do you access parent members in a child class?'},
    {'answer': 'Isolated environment for project dependencies.',
 'category': 'Intermediate',
 'code': '# python -m venv venv\n# source venv/bin/activate',
 'question': 'What is a virtual environment?'},
    {'answer': 'Methods like __init__ that define built-in behavior.',
 'category': 'Intermediate',
 'code': 'class C:\n    def __len__(self): return 0',
 'question': 'What are magic methods (dunder methods)?'},
    {'answer': 'A class of a class, defines class behavior.',
 'category': 'Advanced',
 'code': 'class M(type): pass\nclass C(metaclass=M): pass',
 'question': 'What is a metaclass?'},
    {'answer': 'Keywords for asynchronous coroutines.',
 'category': 'Advanced',
 'code': 'import asyncio\nasync def f():\n    await asyncio.sleep(1)',
 'question': 'Explain async/await.'},
    {'answer': 'Order Python looks for methods in hierarchy.',
 'category': 'Advanced',
 'code': 'print(C.mro())',
 'question': 'What is MRO (Method Resolution Order)?'},
    {'answer': 'Often due to circular references or global accumulation.',
 'category': 'Advanced',
 'code': 'import objgraph\nobjgraph.show_most_common_types()',
 'question': 'Memory leaks in Python?'},
    {'answer': 'Objects defining attribute access behavior.',
 'category': 'Advanced',
 'code': 'class D:\n    def __get__(self, obj, cls): return 0',
 'question': 'What are descriptors?'},
    {'answer': 'Threads share memory; processes have separate memory.',
 'category': 'Advanced',
 'code': 'from multiprocessing import Process\nfrom threading import Thread',
 'question': 'Difference between multi-threading and multi-processing?'},
    {'answer': 'Superset of Python that compiles to C.',
 'category': 'Advanced',
 'code': '# cdef int x = 0',
 'question': 'What is Cython?'},
    {'answer': 'Mainly reference counting + cycle detector.',
 'category': 'Advanced',
 'code': 'import gc\nprint(gc.get_threshold())',
 'question': 'How does garbage collection work in Python?'},
    {'answer': 'Restricts attributes to save memory.',
 'category': 'Advanced',
 'code': "class C:\n    __slots__ = ('a', 'b')",
 'question': 'What are slots?'},
    {'answer': 'Utility module for context managers.',
 'category': 'Advanced',
 'code': 'from contextlib import contextmanager',
 'question': 'What is contextlib?'},
    {'answer': '__new__ creates; __init__ initializes.',
 'category': 'Advanced',
 'code': 'class C:\n    def __new__(cls): return super().__new__(cls)',
 'question': 'Explain the difference between `__new__` and `__init__`.'},
    {'answer': 'Type depends on behavior, not inheritance.',
 'category': 'Advanced',
 'code': 'def f(duck): duck.quack()',
 'question': 'What is duck typing?'},
    {'answer': 'Converting objects to formats like JSON/Pickle.',
 'category': 'Advanced',
 'code': "import json\ns = json.dumps({'a': 1})",
 'question': 'What is serialization?'},
    {'answer': 'Module for higher-order functions.',
 'category': 'Advanced',
 'code': 'from functools import lru_cache',
 'question': 'What is functools?'},
    {'answer': 'Function that behaves differently by first arg type.',
 'category': 'Advanced',
 'code': 'from functools import singledispatch',
 'question': 'What is single dispatch?'},
    {'answer': 'Use profiling, caching, and efficient structures.',
 'category': 'Advanced',
 'code': "import cProfile\ncProfile.run('my_func()')",
 'question': 'How to optimize Python code?'},
    {'answer': 'Allows creating weak references to objects.',
 'category': 'Advanced',
 'code': 'import weakref\nr = weakref.ref(obj)',
 'question': 'What is the weakref module?'},
    {'answer': 'Storing one copy of distinct immutable strings.',
 'category': 'Advanced',
 'code': "import sys\ns = sys.intern('hello')",
 'question': 'What is string interning?'},
    {'answer': 'Suspends function and sends value to caller.',
 'category': 'Advanced',
 'code': 'def f(): yield 1',
 'question': 'Explain the `yield` keyword.'},
    {'answer': 'Generalizations of subroutines for multitasking.',
 'category': 'Advanced',
 'code': 'async def my_coro(): pass',
 'question': 'What are coroutines?'},
    {'answer': 'classmethod gets cls; staticmethod gets neither.',
 'category': 'Advanced',
 'code': '@classmethod\ndef f(cls): pass',
 'question': 'What is the difference between `@staticmethod` and '
             '`@classmethod`?'},
    {'answer': 'Specialized container datatypes.',
 'category': 'Advanced',
 'code': "from collections import Counter\nc = Counter('abac')",
 'question': 'What is the `collections` module?'},
    {'answer': 'Makes an instance callable like a function.',
 'category': 'Advanced',
 'code': 'class C:\n    def __call__(self): pass',
 'question': 'What is `__call__` method?'},
    {'answer': 'Overriding: child redefines. Overloading: not supported natively.',
 'category': 'Advanced',
 'code': 'class B(A):\n    def f(self): pass  # Overriding',
 'question': 'What is method overloading vs overriding?'},
    {'answer': 'Internal renaming to avoid clashes in subclasses.',
 'category': 'Advanced',
 'code': 'class C:\n    def __private(self): pass',
 'question': 'Explain name mangling in Python.'},
    {'answer': 'Package manager for Python.',
 'category': 'Basics',
 'code': '# pip install requests',
 'question': 'What is pip?'},
    {'answer': 'Data interchange format.',
 'category': 'Intermediate',
 'code': 'import json\nd = json.loads(\'{"a": 1}\')',
 'question': 'What is JSON?'},
    {'answer': 'Interface between servers and app frameworks.',
 'category': 'Advanced',
 'code': '# gunicorn myapp:app',
 'question': 'What is WSGI?'},
    {'answer': 'Interface with operating system.',
 'category': 'Intermediate',
 'code': 'import os\nprint(os.getcwd())',
 'question': 'What is os module?'},
    {'answer': 'Interface with the interpreter.',
 'category': 'Intermediate',
 'code': 'import sys\nprint(sys.argv)',
 'question': 'What is sys module?'},
    {'answer': 'HTTP library for making requests.',
 'category': 'Intermediate',
 'code': "import requests\nr = requests.get('https://google.com')",
 'question': 'What is requests module?'},
    {'answer': 'Scaleable testing framework.',
 'category': 'Intermediate',
 'code': 'def test_f(): assert True',
 'question': 'What is pytest?'},
    {'answer': 'Django is batteries-included; Flask is micro.',
 'category': 'Advanced',
 'code': '# Django: MVC-like\n# Flask: Flexible decorators',
 'question': 'What is the difference between Django and Flask?'},
    {'answer': 'Legacy distribution format.',
 'category': 'Intermediate',
 'code': '# Use .whl (Wheels) now',
 'question': 'What is a python egg?'},
    {'answer': 'Built-package distribution format.',
 'category': 'Intermediate',
 'code': '# pip install some_package.whl',
 'question': 'What is a wheel?'},
    {'answer': 'Reads line from user input.',
 'category': 'Basics',
 'code': "name = input('Name: ')",
 'question': 'What is the input() function?'},
    {'answer': 'Use pdb, print, or IDE debuggers.',
 'category': 'Intermediate',
 'code': 'import pdb; pdb.set_trace()',
 'question': 'How to debug Python code?'},
    {'answer': 'Caching results of expensive calls.',
 'category': 'Advanced',
 'code': '@lru_cache\ndef expensive(n): pass',
 'question': 'What is memoization?'},
]
